# will run on all branches
on: push 

jobs:
  build_test:
    runs-on: ubuntu-latest 

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fmps_test
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2.7
          elixir-version: 1.10.3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3 

      - name: Install deps
        run: |
          mix deps.get
          (cd assets && npm install)

      - run: MIX_ENV=test 
      - run: mix ecto.reset  
      - run: mix test
 